apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: dpusriovcni-conf
  annotations:
        k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov
spec:
  config: '{
      "cniVersion": "0.4.0",
      "name": "dpucni",
      "type": "dpucni",
      "ipam": {
          "type": "host-local",
          "subnet": "10.1.2.0/24"
      }
    }'
