apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: dpunfcni-conf
  annotations:
        k8s.v1.cni.cncf.io/resourceName: openshift.io/dpu
spec:
  config: '{
      "cniVersion": "0.4.0",
      "name": "nfcni",
      "type": "nfcni"
    }'
